### PR TITLE
feat: add withMargin prop to Input and DateTime

### PR DESCRIPTION
**Pull request by nartc**
- withMargin is default to `true` to keep the current behavior intact
- withMargin with a `false` value will add `marginless` CSS class to
`ngx-input` and `ngx-date-time` elements

## Summary

Before
image

After
image

## Checklist

- [ ] \*Added unit tests
- [x] \*Added a code reviewer
- [x] Added changes to `/projects/swimlane/ngx-ui/CHANGELOG.md` under HEAD (Unreleased)
- [x] Updated the demo page
- [x] Included screenshots of visual changes

_\*required_

### CODE REVIEW

**Comment by nartc** [comment]
Not ready

**Comment by nartc** [comment]
Please hold off on merging

**Review by luisb90 — APPROVED** [review]
looks good. As per Chau and I's discussion, the margins for other form inputs like `ngx-select` will be investigated separately from this PR and an issue has been created:
https://github.com/swimlane/ngx-ui/issues/514

**Review by marjan-georgiev — APPROVED** [review]
LGTM 👍

**Pull request merged**
