### PR TITLE
Luisb90/update ngx input autosize

### PR DESCRIPTION
**Pull request by luisb90**
## Summary

Worked on updates to ngx-input:

- Replaced the default chrome accessibility number spinner with a custom styled one that matches wireframes for numeric ngx-inputs.
- Added a minWidth property to ngx-input
- Reworked the autosize code, in the previous implementation while the input would grow correctly, it wouldnt size down to smaller inputs (such as small numbers). I've reworked it following the JS method mentioned here: https://css-tricks.com/auto-growing-inputs-textareas/. 

### Edit
There were a lot of edge cases that werent really covered by the above solution, so i decided to go with a third party library, `ngx-autosize-input` 

## Checklist

- [x] \*Added unit tests
- [x] \*Added a code reviewer
- [x] Added changes to `/projects/swimlane/ngx-ui/CHANGELOG.md` under HEAD (Unreleased)
- [x] Updated the demo page
- [x] Included screenshots of visual changes

_\*required_

Old Spinner:
Screen Shot 2020-09-03 at 2 46 37 PM

New Spinner:
Screen Shot 2020-09-03 at 2 45 35 PM

Autosize:
Screen Shot 2020-09-04 at 3 23 46 PM
Screen Shot 2020-09-04 at 4 25 59 PM

### CODE REVIEW

**Comment by duredhel13** [comment]
Are you planning on having design review this PR? I feel like the alignment on the spinners is a bit off.

**Comment by luisb90** [comment]
> Are you planning on having design review this PR? I feel like the alignment on the spinners is a bit off.

yup, Mike is gonna look at it in a bit

**Review by mcwenger — CHANGES_REQUESTED** [review]
1. Given a `min="0"` property, I can use the tickers to go below 0. The field becomes invalid, but current (and html5) functionality won't allow the value from the tickers (spinner).
2. Given a `max="100"` property, I can use the tickers to go above 100.
3. When a placeholder is present, the descenders get cut off (lowercase `g` on the demo page) image
4. Tickers are a bit small—should be 10px equivalent. The top ticker has bottom padding, which makes the targets different sizes. If the font size is increased and padding removed, `.numeric-spinner` aligns middle vertically as it should.
image
5. The ticker's right positioning for the filled variant should be consistent with the left padding. Can we make it a `0` right position for the legacy style? 
image

**Comment by luisb90** [comment]
> 1. Given a `min="0"` property, I can use the tickers to go below 0. The field becomes invalid, but current (and html5) functionality won't allow the value from the tickers (spinner).
> 2. Given a `max="100"` property, I can use the tickers to go above 100.
> 3. When a placeholder is present, the descenders get cut off (lowercase `g` on the demo page) image
> 4. Tickers are a bit small—should be 10px equivalent. The top ticker has bottom padding, which makes the targets different sizes. If the font size is increased and padding removed, `.numeric-spinner` aligns middle vertically as it should.
>    image
> 5. The ticker's right positioning for the filled variant should be consistent with the component's (input's) left padding. Can we make it a `0` right position for the legacy style?
>    image

@mcwenger addressed the comments, you're good to pull and check again

**Review by mcwenger — APPROVED** [review]
Looks great! :+1:

**Comment by Hypercubed** [comment]
@luisb90 @mcwenger Can I suggets adding a little click feedback on the number spinner.  A little on hover color change and some "click" effect?

**Comment by mcwenger** [comment]
@Hypercubed Yes, I love the idea—let's chat on it so I can get a design scope.

**Comment by luisb90** [comment]
> @Hypercubed Yes, I love the idea—let's chat on it so I can get a design scope.

@mcwenger @Hypercubed pushed commit to add scale on hover to the numeric spinner

**Pull request merged**
