### PR TITLE
Add 'showIcons' input to ToggleComponent

### PR DESCRIPTION
**Pull request by mario-alva**
## Summary
Enhancement: Add `showIcons` input to `ToggleComponent`  in order to display the optional icons.
Default value is set to true. But you can turn it off anytime you want.
image

## Checklist

- [x] \*Added unit tests
- [x] \*Added a code reviewer
- [x] Added changes to `/projects/swimlane/ngx-ui/CHANGELOG.md` under HEAD (Unreleased)
- [x] Updated the demo page
- [x] Included screenshots of visual changes

_\*required_

### CODE REVIEW

**Review by Hypercubed — APPROVED** [review]
This looks very good.  Should we make this the default with an option to disable?

**Review by nelsonGuti — APPROVED** [review]
Looks good!

**Comment by nelsonGuti** [comment]
> This looks very good. Should we make this the default with an option to disable?

Yes, good point. It would be nice to have it as default.

**Review by cthompson-Swim — APPROVED** [review]
Looks good... Thanks for pulling up and reviewing with me yesterday!

**Comment by Hypercubed** [comment]
@cthompson-Swim Should this be the default implementaion across the platform?

**Review by mcwenger — APPROVED** [review]
Looks great!

**Pull request merged**
